controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    wheel_seperation: 0.936
    wheel_diameter: 0.2378

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - FL_steering_joint
      - FR_steering_joint
      - BL_steering_joint
      - BR_steering_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

forward_velocity_controller:
  ros__parameters:
    joints:
      - FL_motor_joint
      - FR_motor_joint
      - BL_motor_joint
      - BR_motor_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
